name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts

    steps:
      - uses: actions/checkout@v4

      - name: Install Scarb
        run: curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh

      - name: Add Scarb to PATH
        run: echo "${HOME}/.local/share/scarb/bin" >> $GITHUB_PATH

      - name: Cache Scarb dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.scarb
            target/
          key: ${{ runner.os }}-scarb-${{ hashFiles('**/Scarb.toml') }}
          restore-keys: |
            ${{ runner.os }}-scarb-
        
      - name: Install snforge 0.33.0
        run: |
              # Install Rust toolchain
              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
              source $HOME/.cargo/env
    
              # Add required target
              rustup target add wasm32-unknown-unknown
    
              # Install specific snforge version using cargo
              cargo install --locked --version 0.33.0 snforge --features=rust-serde
    
              # Verify installation
              snforge --version
          
      - name: Install dependencies
        run: scarb clean && scarb fetch

      - name: Build Starknet contracts
        run: scarb build

      - name: Run snforge tests
        run: snforge test        

  nextjs-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
        env:  # Proper indentation here
          NEXT_PUBLIC_API_URL: ${{ github.event_name == 'pull_request' && 'dummy-api-url' || secrets.NEXT_PUBLIC_API_URL }}
          OPENAI_API_KEY: ${{ github.event_name == 'pull_request' && 'dummy-key' || secrets.OPENAI_API_KEY }}
          BRIAN_API_KEY: ${{ github.event_name == 'pull_request' && 'dummy-key' || secrets.BRIAN_API_KEY }}

      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: |
            client/.next/cache
            ${{ github.workspace }}/client/.next/static
          key: ${{ runner.os }}-nextjs-${{ hashFiles('client/package-lock.json') }}-${{ hashFiles('client/**.[jt]sx?') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('client/package-lock.json') }}-

  deploy:
    needs: [check-contracts, nextjs-build-and-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BRIAN_API_KEY: ${{ secrets.BRIAN_API_KEY }}
